#!/bin/bash
git config user.name "rohan22dev"
git config user.email "rohan22dev@users.noreply.github.com"

# Array of meaningful commit messages for UI components
messages=(
  "feat: update docs layout"
  "style: modify global styles"
  "refactor: adjust root layout"
  "fix: update not-found page"
  "feat: redesign landing page"
  "refactor: remove old landing footer"
  "refactor: remove old landing faq"
  "refactor: remove old landing features"
  "refactor: remove old landing hero"
  "refactor: remove old landing how-it-works"
  "refactor: remove old landing navbar"
  "refactor: remove old landing security"
  "refactor: remove old landing vault illustration"
  "feat: update main navbar"
  "feat: improve wallet button"
  "feat: add accordion ui component"
  "feat: add alert ui component"
  "feat: add avatar ui component"
  "feat: add badge ui component"
  "feat: add button ui component"
  "feat: add card ui component"
  "feat: add dialog ui component"
  "feat: add dropdown-menu ui component"
  "feat: add input ui component"
  "feat: add label ui component"
  "feat: add progress ui component"
  "feat: add select ui component"
  "feat: add separator ui component"
  "feat: add sheet ui component"
  "feat: add skeleton ui component"
  "feat: add slider ui component"
  "feat: add sonner ui component"
  "feat: add switch ui component"
  "feat: add table ui component"
  "feat: add tabs ui component"
  "feat: add tooltip ui component"
  "refactor: update nav utilities"
  "refactor: update general utilities"
  "chore: update package-lock"
  "chore: update package.json"
  "feat: add ci/cd pipeline workflow"
  "feat: add vercel deployment config"
)

# Commit the modified files one by one to generate many commits
files=(
  "web/app/docs/page.tsx"
  "web/app/globals.css"
  "web/app/layout.tsx"
  "web/app/not-found.tsx"
  "web/app/page.tsx"
  "web/components/landing/cta-footer.tsx"
  "web/components/landing/faq.tsx"
  "web/components/landing/features.tsx"
  "web/components/landing/hero.tsx"
  "web/components/landing/how-it-works.tsx"
  "web/components/landing/landing-navbar.tsx"
  "web/components/landing/security.tsx"
  "web/components/landing/vault-illustration.tsx"
  "web/components/layout/navbar.tsx"
  "web/components/shared/wallet-button.tsx"
  "web/components/ui/accordion.tsx"
  "web/components/ui/alert.tsx"
  "web/components/ui/avatar.tsx"
  "web/components/ui/badge.tsx"
  "web/components/ui/button.tsx"
  "web/components/ui/card.tsx"
  "web/components/ui/dialog.tsx"
  "web/components/ui/dropdown-menu.tsx"
  "web/components/ui/input.tsx"
  "web/components/ui/label.tsx"
  "web/components/ui/progress.tsx"
  "web/components/ui/select.tsx"
  "web/components/ui/separator.tsx"
  "web/components/ui/sheet.tsx"
  "web/components/ui/skeleton.tsx"
  "web/components/ui/slider.tsx"
  "web/components/ui/sonner.tsx"
  "web/components/ui/switch.tsx"
  "web/components/ui/table.tsx"
  "web/components/ui/tabs.tsx"
  "web/components/ui/tooltip.tsx"
  "web/lib/nav.ts"
  "web/lib/utils.ts"
  "web/package-lock.json"
  "web/package.json"
  ".github/workflows/ci.yml"
  "vercel.json"
)

for i in "${!files[@]}"; do
  file="${files[$i]}"
  msg="${messages[$i]}"
  if [ -e "$file" ] || git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
    git add "$file"
    git commit -m "$msg"
  fi
done

# Then add all remaining untracked files
git add .
git commit -m "feat: complete frontend and ui overhaul"

# Try pushing
git push origin master || git push
